object Versions {
    const val BUILD_TOOLS = "30.0.0"
    const val COMPILE_SDK = 30
    const val MIN_SDK = 21
    const val TARGET_SDK = 30

    const val APPCOMPAT = "1.2.0"
    const val ACTIVITY_KTX = "1.1.0"
    const val ANDROID_GRADLE = "4.1.2"
    const val ARCH_CORE_TESTING = "2.1.0"
    const val CORE_KTX = "1.3.1"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val COROUTINES = "1.3.9"
    const val EASY_PERMISSIONS = "3.0.0"
    const val ESPRESSO_CORE = "3.2.0"
    const val FRAGMENT_KTX = "1.2.5"
    const val GSON = "2.8.6"
    const val GOOGLE_SERVICES = "4.3.4"
    const val GLIDE = "4.12.0"
    const val LOCAL_BROADCAST = "1.0.0"
    const val HAMCREST = "2.1"
    const val HILT = "2.38.1"
    const val HILT_JETPACK = "1.0.0-alpha01"
    const val JUNIT = "4.13"
    const val JUNIT_EXT = "1.1.1"
    const val KOTLIN_GRADLE = "1.4.20"
    const val LIFECYCLE = "2.2.0"
    const val MATERIAL = "1.2.0"
    const val MOCKITO_CORE = "3.5.2"
    const val MOCKITO_KOTLIN = "2.2.0"
    const val RECYCLER_VIEW = "1.1.0"
    const val TIMBER = "4.7.1"
    const val TEST_RUNNER = "1.1.1"
    const val TEST_RULES = "1.1.1"
    const val INTUIT_SSP = "1.0.6"
    const val INTUIT_SDP = "1.0.6"
}
